### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by r17x** [antonybudianto/next-code-antonybudianto#1]
Hi @antonybudianto , This is project is interest (Web Worker) Thanks for make it awesome project.

But, I have some error when pass this sample code

## Produces
- write `self.postMessage("Hello")` in Code Input and Run
- unexpected  

`NIT` I think, need to prevent some code before `eval` 

![image](https://user-images.githubusercontent.com/16365952/120056040-66e1b100-c06c-11eb-876e-7fdd31deb2cf.png)

![image](https://user-images.githubusercontent.com/16365952/120056130-eb343400-c06c-11eb-8382-fb695da38dd9.png)

THank you

**Comment by antonybudianto** [comment]
Thank you for the findings, will fix

**Comment by antonybudianto** [comment]
fixed

**Comment by r17x** [comment]
Good job @antonybudianto
